In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix
from sklearn.model_selection import cross_val_score, GridSearchCV, RandomizedSearchCV
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from keras.utils.np_utils import to_categorical
from sklearn.utils import class_weight
from sklearn.metrics import log_loss
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Model, load_model
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Conv1D
from tensorflow.keras.layers import MaxPooling1D

In [ ]:
import numpy as np # linear algebra
import os # accessing directory structure
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [ ]:
df = pd.read_csv('dataset.csv', delimiter=';')

In [ ]:
df.head()

In [ ]:
df.dropna(axis=0, inplace=True)
df.drop(df.columns[29:-2],axis=1, inplace=True)
df.drop(['T','P','J','QRST','heart_rate'],axis=1, inplace=True)
j = []
for i in df.diagnosis:
    if i > 1 :
        j.append(1)
    else:
        j.append(0)
df.diagnosis = j
df.head()

In [ ]:
df.info()

In [ ]:
df.to_csv('processed.csv')

In [ ]:
print(df.shape)

In [ ]:
import seaborn as sns
sns.countplot(x="diagnosis", data = df)

Reshape X_train and X_test to 3D since Conv1D requires 3D data

In [ ]:
X = df.iloc[:, 0:25]
y = df.iloc[:,25]

In [ ]:
X_train=X.values
X_test=X.values

X_train = X_train.reshape(-1, X_train.shape[1],1)
X_test = X_test.reshape(-1, X_test.shape[1],1)

In [ ]:
print(X_train.shape)
print(X_test.shape)

Convert the Target label to categorical

In [ ]:
target_train=y
target_test=y
Y_train=to_categorical(target_train)
Y_test=to_categorical(target_test)

In [ ]:
print(Y_train.shape)
print(Y_test.shape)

Performance Evaluation Function

In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score
def showResults(test, pred):
    #target_names = ['positive', 'negative']
    # print(classification_report(test, pred, target_names=target_names))
    accuracy = accuracy_score(test, pred)
    precision=precision_score(test, pred, average='weighted')
    f1Score=f1_score(test, pred, average='weighted')
    recallScore=recall_score(test, pred, average='weighted') 
    #loss=log_loss(test,pred)
    print("Accuracy  : {}".format(accuracy))
    print("Precision : {}".format(precision))
    print("F1Score : {}".format(f1Score))
    print("RecallScore : {}".format(recallScore))
    #print("Loss : {}".format(loss))
    cm=confusion_matrix(test, pred)
    print(cm)

Model Defination

# Machine Learning

In [ ]:

data = pd.read_csv("processed.csv")

In [ ]:
data.info()

In [ ]:
print(data.shape)

In [ ]:
X = data.iloc[:, 1:26]
y = data.iloc[:,26]

In [ ]:
y

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

# Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier()
RF.fit(X, y)
predictions = RF.predict(X)
print("*Confusion Matrix for RF: ")
print(confusion_matrix(y, predictions))

Random State: 1
Accuracy: 70.33%
Confusion Matrix:
[[40 12]
 [15 24]]
Random State: 2
Accuracy: 64.84%
Confusion Matrix:
[[31 14]
 [18 28]]
Random State: 3
Accuracy: 73.63%
Confusion Matrix:
[[41  7]
 [17 26]]
Random State: 4
Accuracy: 70.33%
Confusion Matrix:
[[39 10]
 [17 25]]
Random State: 5
Accuracy: 62.64%
Confusion Matrix:
[[32 14]
 [20 25]]
Random State: 6
Accuracy: 69.23%
Confusion Matrix:
[[37 16]
 [12 26]]
Random State: 7
Accuracy: 70.33%
Confusion Matrix:
[[37 13]
 [14 27]]
Random State: 8
Accuracy: 63.74%
Confusion Matrix:
[[37 15]
 [18 21]]
Random State: 9
Accuracy: 72.53%
Confusion Matrix:
[[38 13]
 [12 28]]
Random State: 10
Accuracy: 69.23%
Confusion Matrix:
[[39 13]
 [15 24]]
Random State: 11
Accuracy: 72.53%
Confusion Matrix:
[[37 13]
 [12 29]]
Random State: 12
Accuracy: 74.73%
Confusion Matrix:
[[43 11]
 [12 25]]
Random State: 13
Accuracy: 64.84%
Confusion Matrix:
[[32 10]
 [22 27]]
Random State: 14
Accuracy: 71.43%
Confusion Matrix:
[[36 14]
 [12 29]]
Random State: 1

In [252]:
# import necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.ensemble import RandomForestClassifier

# load the dataset
data = pd.read_csv('processed.csv')

# split the dataset into input features (X) and target variable (y)
X = data.iloc[:, 1:26]
y = data.iloc[:, 26]

# split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=29)

# initialize the random forest classifier and fit it to the training data
rfc = RandomForestClassifier()
rfc.fit(X_train, y_train)

# use the trained model to make predictions on the testing set
y_pred = rfc.predict(X_test)

# evaluate the performance of the model using a confusion matrix
confusion = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion)

# calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: {:.2f}%".format(accuracy*100))

# calculate the sensitivity and specificity of the model
tn, fp, fn, tp = confusion.ravel()
sensitivity = tp / (tp + fn)
specificity = tn / (tn + fp)
print("Sensitivity: {:.2f}%".format(sensitivity*100))
print("Specificity: {:.2f}%".format(specificity*100))

Confusion Matrix:
[[38  7]
 [14 32]]
Accuracy: 76.92%
Sensitivity: 69.57%
Specificity: 84.44%


In [ ]:
confusion = confusion_matrix(y, predictions)
TP = confusion[0, 0]
TN = confusion[1, 1]
FP = confusion[0, 1]
FN = confusion[1, 0]
classification_error = (FP + FN) / float(TP + TN + FP + FN)

print(classification_error)
val1 = accuracy_score(y, predictions) *100
print(val1)
from sklearn import metrics
RF_sensitivity = ((TP / float(FN + TP)))* 100

print(RF_sensitivity)
RF_specificity = ((TN / (TN + FP))) * 100

print(RF_specificity)

In [ ]:
precision=precision_score(y, predictions, average='weighted')
f1Score=f1_score(y, predictions, average='weighted')
recallScore=recall_score(y, predictions, average='weighted') 

In [ ]:
print("Precision : {}".format(precision))
print("F1Score : {}".format(f1Score))
print("RecallScore : {}".format(recallScore))

# Decision Tree

In [ ]:
from sklearn import tree
DT = tree.DecisionTreeClassifier()
DT.fit(X, y)
predictions = DT.predict(X)
print("*Confusion Matrix for DT: ")
print(confusion_matrix(y, predictions))

In [ ]:
confusion = confusion_matrix(y, predictions)
TP = confusion[0, 0]
TN = confusion[1, 1]
FP = confusion[0, 1]
FN = confusion[1, 0]
classification_error = (FP + FN) / float(TP + TN + FP + FN)

print(classification_error)
val2 = accuracy_score(y, predictions) *100
print(val2)
from sklearn import metrics
DT_sensitivity = ((TP / float(FN + TP)))* 100

print(DT_sensitivity)
DT_specificity = ((TN / (TN + FP))) * 100

print(DT_specificity)

In [ ]:
precision=precision_score(y, predictions, average='weighted')
f1Score=f1_score(y, predictions, average='weighted')
recallScore=recall_score(y, predictions, average='weighted') 

In [ ]:
print("Precision : {}".format(precision))
print("F1Score : {}".format(f1Score))
print("RecallScore : {}".format(recallScore))

# Support Vector Machine

In [ ]:
from sklearn.svm import SVC
clf = SVC(gamma='auto')
clf.fit(X, y)
predictions = clf.predict(X)
print("*Confusion Matrix for SVM: ")
print(confusion_matrix(y, predictions))
confusion = confusion_matrix(y, predictions)
TP = confusion[0, 0]
TN = confusion[1, 1]
FP = confusion[0, 1]
FN = confusion[1, 0]
classification_error = (FP + FN) / float(TP + TN + FP + FN)

print(classification_error)
val7 = accuracy_score(y, predictions) *100
print(val7)
from sklearn import metrics
SVM_sensitivity = ((TP / float(FN + TP)))* 100

print(SVM_sensitivity)
SVM_specificity = ((TN / (TN + FP))) * 100

print(SVM_specificity)

In [ ]:
precision=precision_score(y, predictions, average='weighted')
f1Score=f1_score(y, predictions, average='weighted')
recallScore=recall_score(y, predictions, average='weighted')

print("Precision : {}".format(precision))
print("F1Score : {}".format(f1Score))
print("RecallScore : {}".format(recallScore))

# Voting Classifier

In [ ]:
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
clf1 = SVC(gamma='auto')
clf2 = RandomForestClassifier(n_estimators=10, random_state=1)
clf3 = DecisionTreeClassifier()
eclf1 = VotingClassifier(estimators=[('lr', clf1), ('rf', clf2), ('dt', clf3)], voting='hard')
eclf1.fit(X, y)
predictions = eclf1.predict(X)
print("*Confusion Matrix for Voting Classifier: ")
print(confusion_matrix(y, predictions))

In [ ]:
confusion = confusion_matrix(y, predictions)
TP = confusion[0, 0]
TN = confusion[1, 1]
FP = confusion[0, 1]
FN = confusion[1, 0]
classification_error = (FP + FN) / float(TP + TN + FP + FN)

print(classification_error)
val8 = accuracy_score(y, predictions) * 100
print(val8)
from sklearn import metrics
VOT_sensitivity = ((TP / float(FN + TP))) * 100

print(VOT_sensitivity)
VOT_specificity = ((TN / (TN + FP))) * 100

print(VOT_specificity)

In [ ]:
precision=precision_score(y, predictions, average='weighted')
f1Score=f1_score(y, predictions, average='weighted')
recallScore=recall_score(y, predictions, average='weighted')

print("Precision : {}".format(precision))
print("F1Score : {}".format(f1Score))
print("RecallScore : {}".format(recallScore))

# Accuracy Comparison

In [ ]:
score = [val1,val2,val3,val4,val5,val6,val7,val8,val9,val10,cnn[19]*100,hyd[50]*100,lstm[50]*100,bilstm[50]*100,hyd1[50]*100]

In [ ]:
#make variabel for save the result and to show it
classifier = ('Random Forest','Decision Tree','Support Vector Machine','Voting Classifier')
y_pos = np.arange(len(classifier))
print(y_pos)
print(score)

In [ ]:
import matplotlib.pyplot as plt2
plt2.barh(y_pos, score, align='center', alpha=0.5,color='blue')
plt2.yticks(y_pos, classifier)
plt2.xlabel('Score')
plt2.title('Classification Performance')
plt2.show()

In [ ]:
import joblib
filename = 'model.sav'
joblib.dump(eclf1, filename)